//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAM.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RAM.Domain.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu item is already checked..
        /// </summary>
        public static string AlreadyChecked {
            get {
                return ResourceManager.GetString("AlreadyChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu item is already unchecked..
        /// </summary>
        public static string AlreadyUnchecked {
            get {
                return ResourceManager.GetString("AlreadyUnchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File record&apos;s creation date cannot be from future..
        /// </summary>
        public static string DateOutOfRange {
            get {
                return ResourceManager.GetString("DateOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot save statement&apos;s argument with the same value..
        /// </summary>
        public static string DuplicatedArgument {
            get {
                return ResourceManager.GetString("DuplicatedArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot save menu item&apos;s header with the same value..
        /// </summary>
        public static string DuplicatedHeader {
            get {
                return ResourceManager.GetString("DuplicatedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot save file record&apos;s input members with the same value..
        /// </summary>
        public static string DuplicatedInputMembers {
            get {
                return ResourceManager.GetString("DuplicatedInputMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot save statement&apos;s instruction with the same value..
        /// </summary>
        public static string DuplicatedInstruction {
            get {
                return ResourceManager.GetString("DuplicatedInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot save menu item&apos;s is checked with the same value..
        /// </summary>
        public static string DuplicatedIsChecked {
            get {
                return ResourceManager.GetString("DuplicatedIsChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot save statement&apos;s label with the same value..
        /// </summary>
        public static string DuplicatedLabel {
            get {
                return ResourceManager.GetString("DuplicatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot save tape member&apos;s number with the same value..
        /// </summary>
        public static string DuplicatedNumber {
            get {
                return ResourceManager.GetString("DuplicatedNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot save file record&apos;s statements with the same value..
        /// </summary>
        public static string DuplicatedStatements {
            get {
                return ResourceManager.GetString("DuplicatedStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot save tape member&apos;s value with the same value..
        /// </summary>
        public static string DuplicatedValue {
            get {
                return ResourceManager.GetString("DuplicatedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu item&apos;s header cannot be empty..
        /// </summary>
        public static string EmptyHeader {
            get {
                return ResourceManager.GetString("EmptyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to file cannot be empty..
        /// </summary>
        public static string EmptyPath {
            get {
                return ResourceManager.GetString("EmptyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record name cannot be empty..
        /// </summary>
        public static string EmptyRecordName {
            get {
                return ResourceManager.GetString("EmptyRecordName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot save file record&apos;s comment with the same value..
        /// </summary>
        public static string FileRecord_DuplicatedComment {
            get {
                return ResourceManager.GetString("FileRecord_DuplicatedComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot save tape member&apos;s number with value less than zero..
        /// </summary>
        public static string NumberLessThanZero {
            get {
                return ResourceManager.GetString("NumberLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot save statement&apos;s comment with the same value..
        /// </summary>
        public static string Statement_DuplicatedComment {
            get {
                return ResourceManager.GetString("Statement_DuplicatedComment", resourceCulture);
            }
        }
    }
}
